apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gloo
spec:
  host: gloo.baloise.dev
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gateway-proxy
    weight: 100
status:
  ingress:
    - routerName: router

