apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: harbor
  name: harbor
spec:
  host: {{ .Values.service.ingress.hosts.core }}
  path: /
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "harbor.portal" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - routerName: router